import Head from 'next/head';

const AuthLayout = ({ children }: any) => {
  return (
    <>
      <Head>
        <title>Resume Screening</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-light_neutral_400 min-h-screen overflow-scroll  pb-[40px]">{children}</main>
    </>
  );
};

export default AuthLayout;
