import Head from 'next/head';
import Navbar from './Navbar';
import { useContext } from 'react';
import  ModalContext  from '@/components/Modal'

const Layout = ({ children }: any) => {
    const {isOpen} = useContext(ModalContext);
    return (
        <>
            <Head>
                <title>Resume Screening</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header>
                <Navbar />
            </header>
            <main className={`${isOpen? ' opacity-75 absolute inset-0' : ''}bg-light_neutral_400 h-screen overflow-scroll  `}>
                {children}
            </main>
        </>
    )
}

export default Layout;