import Head from 'next/head';
import Navbar from './Navbar';

const Layout = ({ children }: any) => {
  return (
    <>
      <Head>
        <title>Resume Screening</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navbar />
      </header>
      <main className={`bg-light_neutral_400 min-h-screen overflow-scroll  `}>{children}</main>
    </>
  );
};

export default Layout;
