
const educationOptions = [
    { value: 'SMA', label: 'SMA' },
    { value: 'S1', label: 'S1' },
    { value: 'S2', label: 'S2' },
    { value: 'S3', label: 'S3' },
]

const domicileOptions = [
    { value: 'Jakarta', label: 'Jakarta' },
    { value: 'Bandung', label: 'Bandung' },
    { value: 'Surabaya', label: 'Surabaya' },
    { value: 'Semarang', label: 'Semarang' },
    { value: 'Yogyakarta', label: 'Yogyakarta' },
    { value: 'Bali', label: 'Bali' },
    { value: 'Lombok', label: 'Lombok' },
    { value: 'Makassar', label: 'Makassar' },
    { value: 'Medan', label: 'Medan' },
    { value: 'Palembang', label: 'Palembang' },
    { value: 'Balikpapan', label: 'Balikpapan' },
    { value: 'Manado', label: 'Manado' },
    { value: 'Papua', label: 'Papua' },
    { value: 'Malang', label: 'Malang' },
    { value: 'Bogor', label: 'Bogor' },
    { value: 'Bekasi', label: 'Bekasi' },
    { value: 'Tangerang', label: 'Tangerang' },
    { value: 'Depok', label: 'Depok' },
    { value: 'Banten', label: 'Banten' },
    { value: 'Lampung', label: 'Lampung' },
    { value: 'Jambi', label: 'Jambi' },
    { value: 'Padang', label: 'Padang' },
    { value: 'Pekanbaru', label: 'Pekanbaru' },
    { value: 'Pontianak', label: 'Pontianak' },
    { value: 'Banjarmasin', label: 'Banjarmasin' },
    { value: 'Samarinda', label: 'Samarinda' },
    { value: 'Mamuju', label: 'Mamuju' },
    { value: 'Majene', label: 'Majene' },
    { value: 'Makale', label: 'Makale' },
    { value: 'Palopo', label: 'Palopo' },
    { value: 'Palu', label: 'Palu' },
    { value: 'Gorontalo', label: 'Gorontalo' },
    { value: 'Ambon', label: 'Ambon' },
    { value: 'Ternate', label: 'Ternate' },
    { value: 'Kendari', label: 'Kendari' },
    { value: 'Jayapura', label: 'Jayapura' },
    { value: 'Sorong', label: 'Sorong' },
    { value: 'Merauke', label: 'Merauke' },
    { value: 'Timika', label: 'Timika' },
    { value: 'Biak', label: 'Biak' },
]

const companyOptions = [
    { value: 'PT. Astra International Tbk', label: 'PT. Astra International Tbk' },
    { value: 'PT. Astra Honda Motor', label: 'PT. Astra Honda Motor' },
    { value: 'PT. Astra Otoparts Tbk', label: 'PT. Astra Otoparts Tbk' },
    { value: 'PT. Federal International Finance', label: 'PT. Federal International Finance' },
    { value: 'PT. Toyota Astra Financial Services', label: 'PT. Toyota Astra Financial Services' },
    { value: 'PT. Toyota Motor Manufacturing Indonesia', label: 'PT. Toyota Motor Manufacturing Indonesia' },
]

export { educationOptions, domicileOptions, companyOptions }